apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bro.fullname" . }}-runner-suricata-search 
data:
  suricata-alerts.json: | 
    {
      "type": "search",
      "search": {
        "title": "SURICATA-Alerts",
        "description": "",
        "hits": 0,
        "columns": [
          "_source"
        ],
        "sort": [
          "@timestamp",
          "desc"
        ],
        "version": 1,
        "kibanaSavedObjectMeta": {
          "searchSourceJSON": "{\"index\":\"suricata-*\",\"query\":{\"query_string\":{\"query\":\"event_type:alert\",\"analyze_wildcard\":true}},\"filter\":[],\"highlight\":{\"pre_tags\":[\"@kibana-highlighted-field@\"],\"post_tags\":[\"@/kibana-highlighted-field@\"],\"fields\":{\"*\":{}},\"require_field_match\":false,\"fragment_size\":2147483647}}"
        }
      }
    }